#端口
server:
  port: 8078

swagger2:
  enable: true

#配置日志级别
logging:
  level: info
  file: home/logs.log

spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #springboot 使用spring.profiles.active 选择要激活哪个环境块
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://rm-8vb13nmd5388n09m6wo.mysql.zhangbei.rds.aliyuncs.com:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    userName: zhaofu
    password: 2MiaoMiao
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 5
      min-idle: 1
      initial-size: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 360000
      minEvictableIdleTimeMillis: 360000
    # 通过别名的方式配置扩展插件，多个英文逗号分隔，常用的插件有：
    # 监控统计用的filter:stat
    # 日志用的filter:log4j
    # 防御sql注入的filter:wall
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  mail:
    host: smtp.163.com
    username: 17765114126@163.com #自己的邮箱账号
    password: YXIDYBPHLBGNCNQP  #这个不是登录密码而是163授权登录的密码
    default-encoding: UTF-8
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        ssl:
          enable: true

  redis:
    host: 39.101.184.47
    port: 6379
    password:
    # Redis数据库索引（默认为0）
    database: 0
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间
#        max-wait: 6000
        #最大空闲连接
        max-idle: 8
        #最小空闲连接
        min-idle: 0
        timeout: 5000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config.table-prefix: bl_
  config.db-config:
    id-type: auto
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 去除启动时大量的Positive matches信息
logging.level.org.springframework.boot.autoconfigure: ERROR


#配置文件传输
servlet:
  multipart:
    enabled: true
    file-size-threshold: 0
    #单个数据的大小
    max-file-size: 500MB
    #总数据的大小
    max-request-size: 1000MB

---
server:
  port: 8080
spring:
  profiles: dev #配置环境的名称


---
server:
  port: 8079
spring:
  profiles: prod  #配置环境的名称